### ISSUE TITLE
s3 支持 symlink

### ISSUE THREAD

**Issue by bbtfr** [megvii-research/megfile#13]
目前 megfile 认为 文件系统中 symlink 是一个文件，s3 中不存在 symlink
期望修改为，文件系统中 symlink 行为和标准库一致，s3 中 symlink 使用对象 headers 中特殊的 key 来标注，行为模仿文件系统中的 symlink

**Comment by bbtfr** [comment]
还需要在 walk 等函数上实现 followlinks

**Comment by LoveEatCandy** [comment]
2.0.1 全部完成
