### ISSUE TITLE
v1.0.0执行smart_copy报错

### ISSUE THREAD

**Issue by qq332982511** [megvii-research/megfile#145]
下面的脚本在v1.0.0上执行报错, 但在v0.1.2上可以正常执行
```python
import megfile
url = 'https://data.megengine.org.cn/models/weights/resnet50_fbaug_76254_4e14b7d1.pkl'
dst = './xxx.pkl'
megfile.smart_copy(url, dst)
```
![image](https://user-images.githubusercontent.com/12827094/181735090-1021218a-0e3e-486f-b173-8b61dee44003.png)

**Comment by LoveEatCandy** [comment]
megfile 1.0.0.post5 已经修复了这个 bug，请 pip install -U megfile 使用，
如果问题依旧存在，请 reopen 此 issue
