### ISSUE TITLE
改进 S3PrefetchReader 随机访问性能

### ISSUE THREAD

**Issue by bbtfr** [megvii-research/megfile#15]
在 s3_buffered_open buffered=True 变成默认值后，随机访问的性能下降了许多，需要想办法提回来

**Comment by LoveEatCandy** [comment]
这个 [PR](https://github.com/megvii-research/megfile/pull/359) 将默认 `buffered` 改为 `False`，并且对 pickle 文件做了特判，会包一层 `BufferedReader` 或 `BufferedWriter`
