### ISSUE TITLE
is_file提示没有参数followlinks

### ISSUE THREAD

**Issue by Flyooofly** [megvii-research/megfile#161]
TypeError: is_file() got an unexpected keyword argument 'followlinks'
![image](https://user-images.githubusercontent.com/31236750/196965919-da3f450c-8d1e-4310-92fd-6525e0908bc6.png)

**Comment by LoveEatCandy** [comment]
detectron2:// 这个 protocol 不是官方支持的，请和实现相关功能的人员联系，支持一下 megfile 的接口新参数followlinks

**Comment by LoveEatCandy** [comment]
如果您在旷视，可以联系 penghongyang 加入客服群

**Comment by YiqunChen1999** [comment]
请问要降到哪个版本的megfile可以避免这一问题？

**Comment by LoveEatCandy** [comment]
> 请问要降到哪个版本的megfile可以避免这一问题？

可以试试 0.0.11
