### ISSUE TITLE
请求实现官方版本 smart_lstat

### ISSUE THREAD

**Issue by DIYer22** [megvii-research/megfile#182]
```
~/anaconda3/lib/python3.8/tarfile.py in gettarinfo(self, name, arcname, fileobj)                
   1830         if fileobj is None:                                                             
   1831             if not self.dereference:                                                    
-> 1832                 statres = os.lstat(name)                                                
   1833             else:                                                                       
   1834                 statres = os.stat(name)                                                 
                                                                                                
FileNotFoundError: [Errno 2] No such file or directory: 's3://yl-dataset/carton/2301_huafeng/raw
_2scan/2023-03-07-13_39_37.35595'
```

![image](https://user-images.githubusercontent.com/10448025/226160956-709cfed5-eca3-415a-83fe-573b500c1343.png)

**Comment by LoveEatCandy** [comment]
看起来和 smart_lstat 关系不大，tarfile 只能读本地文件，FileNotFoundError 指的是 tarfile 无法在本地文件系统找到文件：s3://yl-dataset/carton/2301_huafeng/raw
_2scan/2023-03-07-13_39_37.35595。但是我们会加上 smart_lstat 方法

**Comment by LoveEatCandy** [comment]
如果你是 megvii 内部人员，可以尝试使用 `restore` 库，`from restore.archive import tarfile_open`

**Comment by DIYer22** [comment]
> 看起来和 smart_lstat 关系不大，tarfile 只能读本地文件，FileNotFoundError 指的是 tarfile 无法在本地文件系统找到文件：s3://yl-dataset/carton/2301_huafeng/raw _2scan/2023-03-07-13_39_37.35595。但是我们会加上 smart_lstat 方法

我魔改了标准库, 通过侵入式地把标准库中的 path 操作替换为了 megfile, 可以在不改动代码的情况下, 让 Python 程序兼容 oss. 所以非常看中和标准库的一致性, 期待添加 `smart_lstat`!
