### ISSUE TITLE
smart_copy 报错 TypeError: stat() got an unexpected keyword argument 'follow_symlinks'

### ISSUE THREAD

**Issue by chen-2569** [megvii-research/megfile#243]
megfile：2.1.1.post1
smart_copy 时报错 TypeError: stat() got an unexpected keyword argument 'follow_symlinks'
复现步骤
``` python
from megfile import smart_copy
smart_copy("https://www.megengine.org.cn/doc/stable/zh/index.html", "/home/xxx/download/index.html")
```

<img width="849" alt="截屏2023-07-06 18 26 41" src="https://github.com/megvii-research/megfile/assets/54138714/beed5149-3224-4dda-ab65-807a8cb3833c">

**Comment by LoveEatCandy** [comment]
升级到 2.1.1.post2 可以解决此问题
