### ISSUE TITLE
求给个阿里云oss的样例

### ISSUE THREAD

**Issue by ae86208** [megvii-research/megfile#26]
用oss2 感觉一夜回到解放前，自己捣鼓了几次结果403……
阿里云oss现在只支持 [Virtual Hosted-Style Requests](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html)，估计和这个有关

啥时候能用了我就去地推 :)

**Comment by bbtfr** [comment]
因为没 oss2 的测试环境，所以我先猜猜这样说不定可以，参考：https://blog.csdn.net/libing_thinking/article/details/79664059

1. 配置环境变量 `OSS_ENDPOINT` 或者代码里设置 `megfile.s3.endpoint_url = 'http://oss-cn-hangzhou.aliyuncs.com'`
    这里的 endpoint_url 我不太确定应该填啥
2. 用 awscli 配置一下 `aws configure set s3.addressing_style virtual`

**Comment by ae86208** [comment]
很强，可以用了

**Comment by xyb** [comment]
@bbtfr Is there any chance Megfile includes automatic detection of the cloud environment and gives a more user-friendly message to set up virtual addressing style in case of access 403 failure?

**Comment by bbtfr** [comment]
可能需要验证一下我们是不是支持在 .aws/config 里配置 endpoint_url

**Comment by bbtfr** [comment]
@ae86208 感觉 endpoint 通过环境变量或者代码来配置还是有点麻烦的，所以讨论了下，也准备放在配置文件里
实现上参考 https://github.com/wbingli/awscli-plugin-endpoint

支持在 `~/.aws/config` 里配置 s3.endpoint_url 来配置 endpoint
例如：

```
$ cat ~/.aws/config
[default]

s3 =
    addressing_style = virtual
    endpoint_url = http://oss-cn-hangzhou.aliyuncs.com
```

配置时可以直接编辑这个文件，或者 `aws configure set s3.endpoint_url http://oss-cn-hangzhou.aliyuncs.com`

注：仅对 refile 生效，awscli 如果使用这个功能，需要加上 https://github.com/wbingli/awscli-plugin-endpoint 这个插件，配置方法参考它的 readme

PR: https://github.com/megvii-research/megfile/pull/46

**Comment by ae86208** [comment]
> 注：仅对 refile 生效

应该是megfile吧

**Comment by bbtfr** [comment]
> > 注：仅对 refile 生效
> 
> 应该是megfile吧

漏嘴了
