### ISSUE TITLE
API文档缺失

### ISSUE THREAD

**Issue by StepInfinite** [megvii-research/megfile#387]
![image](https://github.com/megvii-research/megfile/assets/170945803/2ec6227b-33cb-41d8-939f-5adc64a48b4a)
以前每个submodule能看到对应的api function，现在这些api都没了

**Comment by LoveEatCandy** [comment]
这是 ci 构建日志的问题，我们尽快修一下

**Comment by LoveEatCandy** [comment]
先回滚到 3.0.6.post1 的文档了，你先看着，和 3.1.0 差别可以在 changlog 中看到：https://github.com/LoveEatCandy/megfile/blob/main/CHANGELOG.md#310---20240709

**Comment by LoveEatCandy** [comment]
已经修复了，感谢您的积极反馈

**Comment by LoveEatCandy** [comment]
> https://megvii-research.github.io/megfile/megfile.smart.html, 文档貌似不能查询api了

感谢提醒，修复了
