### ISSUE TITLE
[feature request] 支持某种 Protocol aliasing

### ISSUE THREAD

**Issue by bigeagle** [megvii-research/megfile#403]
例如可以配置
```
oss3://xxxxx
```
等效于
```
s3+oss3://xxxx
```

**Comment by bbtfr** [comment]
😂 想了想对这个需求，最麻烦的地方是，megfile 没设计自己的配置文件，alias 没地方存
实现路径似乎可以是

1. 设计一个 megfile 的，或者仅仅是 alias 的配置文件
2. 设计个 AliasPath，是其他 Path 的一个简单 wrapper

**Comment by LoveEatCandy** [comment]
3.1.4 支持了，感谢 @bbtfr ，文档：https://megvii-research.github.io/megfile/readme.html#create-aliases
