### ISSUE TITLE
4.0 上一些可以不向前兼容的功能讨论

### ISSUE THREAD

**Issue by bbtfr** [megvii-research/megfile#433]
1. 虽然在 3.0 上改了 sftp 的定义，// 代表绝对路径，但发现这个定义有些真的使用了 sftp 的用户老踩坑，感觉这设计比较反直觉，可能还是改回只支持绝对路径比较好？最近有人锤我说拷贝完没文件，吓得我屁滚尿流，后来发现是 sftp 相对路径的问题
2. 命令行里的 cp -r / sync，目前行为和 cp 对齐，根据输出目录是否存在，是否是个目录行为不一致，这个用起来也挺容易吃瘪，感觉 cp 这个行为就是不是好定义，容易拷贝完多一层目录；这个我需要找点例子
3. 有需求希望 sync 的时候支持输入目录是 glob，类似 aws cli 的行为，这可能是个 feature request 了不该记在这

**Comment by LoveEatCandy** [comment]
1. sftp 相对路径这个不太好去，我记得有人用当时才加的，有的确实是不确定 HOME，刚需相对路径
2. cp 命令现在是有点怪
3. glob 这个已经支持了，比如 `megfile sync "aa/*" bbb`，注意 glob path 加上引号就行
