### ISSUE TITLE
CLI cp 的行为

### ISSUE THREAD

**Issue by bbtfr** [megvii-research/megfile#89]
目前 CLI 拷贝的行为是 `megfile cp src dst` 把 src 拷到 dst，如果 dst 是个目录会报是个目录的错，这点跟 `cp` 不一样
期望改为和 cp 行为一致：

1. 如果目标位置是个目录，把文件以 basename 拷进去
2. 加 `-T / --no-target-directory` 保持目前行为

mv 看起来也是

**Comment by bbtfr** [comment]
@LoveEatCandy

**Comment by LoveEatCandy** [comment]
Done
https://github.com/megvii-research/megfile/pull/90
